services:
  go-api:
    build:
      context: .
      target: go-server
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "./backend:/usr/src/app"
    environment:
      SECRET_KEY:
      POSTGRES_DB: are_they_playing
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      ADMIN_PASSWORD:    
      INTERNAL_SERVICE_AUTH_KEY:

  ionic-gui:
    build:
      context: .
      target: node
    restart: unless-stopped
    ports:
      - "8100:80"
    volumes:
      - "./frontend:/app"

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: are_they_playing
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - database:/var/lib/postgresql/data

  envoy:
    image: envoyproxy/envoy:v1.33-latest
    restart: unless-stopped
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  python_service:
    build: 
      context: .
      target: python
    restart: unless-stopped
    environment:
      SCRIPT_NAME:
      INTERNAL_SERVICE_AUTH_KEY:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
    volumes:
      - ./data_grabber:/usr/src/app
    stdin_open: true
    tty: true
    network_mode: host

  message_broker:
    image: rabbitmq:4.1
    hostname: rabbit
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "8200:15672"
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  database:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local