services:
  go-api:
    build:
      context: .
      target: go-server
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "./backend:/usr/src/app"
    environment:
      SECRET_KEY:
      POSTGRES_DB: are_they_playing
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      ADMIN_PASSWORD:    
      INTERNAL_SERVICE_AUTH_KEY:

  ionic-gui:
    build:
      context: .
      target: node
    restart: unless-stopped
    ports:
      - "8100:80"
    volumes:
      - "./frontend:/app"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: are_they_playing
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - database:/var/lib/postgresql/data

  envoy:
    image: envoyproxy/envoy:v1.33-latest
    restart: unless-stopped
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  python_service:
    build: 
      context: .
      target: python
    environment:
      SCRIPT_NAME:
      INTERNAL_SERVICE_AUTH_KEY:
    volumes:
      - ./microservices:/usr/src/app
    stdin_open: true
    tty: true

volumes:
  database: