services:
  go-api:
    build:
      context: .
      target: go-server
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "./backend:/usr/src/app"

  ionic-gui:
    build:
      context: .
      target: node
    restart: unless-stopped
    ports:
      - "8100:80"
    volumes:
      - "./frontend:/app"


  envoy:
    image: envoyproxy/envoy:v1.33-latest
    restart: unless-stopped
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
