version: '3'

tasks:
  generate:
    cmds:
      - buf generate
  run:
    cmds:
      - task: run-backend
      - task: run-frontend
  run-backend:
    cmds:
      - GOFLAGS="-mod=mod" go build -C backend internal/server.go
      - ./backend/server
  run-frontend:
    dir: frontend
    cmds:
      - ionic serve
  build-frontend:
    dir: frontend
    cmds:
      - ionic build
      - ionic cap copy
      - ionic cap sync
